### PR TITLE
kodi 19 (matrix) support

### PR DESCRIPTION
**Pull request by Palindrones**

### CODE REVIEW

**Review by cibboy — COMMENTED** [review]
Hi @Palindrones,
Awesome contribution, thank you! Unfortunately I'm not currently using Kodi, but I guess you tested you changes on Matrix?

**Comment by Palindrones** [comment]
hello @cibboy,
I tested the changes on android OS.

**Comment by Palindrones** [comment]
hello @cibboy,
I have tested this on Matrix  with Android OS.

**Comment by cibboy** [comment]
Thank you again for your changes, I will now merge them with main.

**Review by cibboy — APPROVED** [review]

**Pull request merged**
